version: '3.8'

services:
  mysql_dev:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: dev_api
      MYSQL_USER: dev
      MYSQL_PASSWORD: teste
    ports:
      - "3307:3306"       
    volumes:
      - mysql_dev_data:/var/lib/mysql

  app:
    build: .
    container_name: flask_app
    command: python app.py
    volumes:
      - .:/app
    depends_on:
      - mysql_dev
    ports:
      - "5000:5000"

volumes:
  mysql_dev_data: