INSERT INTO cartas (nome, uri_carta, raridade) VALUES
('Snivy', 'https://den-cards.pokellector.com/1/Snivy.BLW.1.mobile.jpg', 'Comum'),
('Snivy', 'https://den-cards.pokellector.com/1/Snivy.BLW.2.mobile.jpg', 'Comum'),
('Servine', 'https://den-cards.pokellector.com/1/Servine.BLW.3.mobile.jpg', 'Incomum'),
('Servine', 'https://den-cards.pokellector.com/1/Servine.BLW.4.mobile.jpg', 'Incomum'),
('Serperior', 'https://den-cards.pokellector.com/1/Serperior.BLW.5.mobile.jpg', 'Rara'),
('Serperior', 'https://den-cards.pokellector.com/1/Serperior.BLW.6.mobile.jpg', 'Rara'),
('Pansage', 'https://den-cards.pokellector.com/1/Pansage.BLW.7.mobile.jpg', 'Comum'),
('Simisage', 'https://den-cards.pokellector.com/1/Simisage.BLW.8.mobile.jpg', 'Incomum'),
('Petilil', 'https://den-cards.pokellector.com/1/Petilil.BLW.9.mobile.jpg', 'Comum'),
('Lilligant', 'https://den-cards.pokellector.com/1/Lilligant.BLW.10.mobile.jpg', 'Rara'),
('Maractus', 'https://den-cards.pokellector.com/1/Maractus.BLW.11.mobile.jpg', 'Incomum'),
('Maractus', 'https://den-cards.pokellector.com/1/Maractus.BLW.12.mobile.jpg', 'Rara'),
('Deerling', 'https://den-cards.pokellector.com/1/Deerling.BLW.13.mobile.jpg', 'Comum'),
('Sawsbuck', 'https://den-cards.pokellector.com/1/Sawsbuck.BLW.14.mobile.jpg', 'Rara'),
('Tepig', 'https://den-cards.pokellector.com/1/Tepig.BLW.15.mobile.jpg', 'Comum'),
('Tepig', 'https://den-cards.pokellector.com/1/Tepig.BLW.16.mobile.jpg', 'Comum'),
('Pignite', 'https://den-cards.pokellector.com/1/Pignite.BLW.17.mobile.jpg', 'Incomum'),
('Pignite', 'https://den-cards.pokellector.com/1/Pignite.BLW.18.mobile.jpg', 'Incomum'),
('Emboar', 'https://den-cards.pokellector.com/1/Emboar.BLW.19.mobile.jpg', 'Rara'),
('Emboar', 'https://den-cards.pokellector.com/1/Emboar.BLW.20.mobile.jpg', 'Rara'),
('Pansear', 'https://den-cards.pokellector.com/1/Pansear.BLW.21.mobile.jpg', 'Comum'),
('Simisear', 'https://den-cards.pokellector.com/1/Simisear.BLW.22.mobile.jpg', 'Incomum'),
('Darumaka', 'https://den-cards.pokellector.com/1/Darumaka.BLW.23.mobile.jpg', 'Comum'),
('Darumaka', 'https://den-cards.pokellector.com/1/Darumaka.BLW.24.mobile.jpg', 'Incomum'),
('Darmanitan', 'https://den-cards.pokellector.com/1/Darmanitan.BLW.25.mobile.jpg', 'Rara'),
('Reshiram', 'https://den-cards.pokellector.com/1/Reshiram.BLW.26.mobile.jpg', 'Rara'),
('Oshawott', 'https://den-cards.pokellector.com/1/Oshawott.BLW.27.mobile.jpg', 'Comum'),
('Oshawott', 'https://den-cards.pokellector.com/1/Oshawott.BLW.28.mobile.jpg', 'Comum'),
('Dewott', 'https://den-cards.pokellector.com/1/Dewott.BLW.29.mobile.jpg', 'Incomum'),
('Dewott', 'https://den-cards.pokellector.com/1/Dewott.BLW.30.mobile.jpg', 'Incomum'),
('Samurott', 'https://den-cards.pokellector.com/1/Samurott.BLW.31.mobile.jpg', 'Rara'),
('Samurott', 'https://den-cards.pokellector.com/1/Samurott.BLW.32.mobile.jpg', 'Rara'),
('Panpour', 'https://den-cards.pokellector.com/1/Panpour.BLW.33.mobile.jpg', 'Comum'),
('Simipour', 'https://den-cards.pokellector.com/1/Simipour.BLW.34.mobile.jpg', 'Incomum'),
('Basculin', 'https://den-cards.pokellector.com/1/Basculin.BLW.35.mobile.jpg', 'Incomum'),
('Ducklett', 'https://den-cards.pokellector.com/1/Ducklett.BLW.36.mobile.jpg', 'Comum'),
('Swanna', 'https://den-cards.pokellector.com/1/Swanna.BLW.37.mobile.jpg', 'Rara'),
('Alomomola', 'https://den-cards.pokellector.com/1/Alomomola.BLW.38.mobile.jpg', 'Incomum'),
('Alomomola', 'https://den-cards.pokellector.com/1/Alomomola.BLW.39.mobile.jpg', 'Rara'),
('Blitzle', 'https://den-cards.pokellector.com/1/Blitzle.BLW.40.mobile.jpg', 'Comum'),
('Blitzle', 'https://den-cards.pokellector.com/1/Blitzle.BLW.41.mobile.jpg', 'Comum'),
('Zebstrika', 'https://den-cards.pokellector.com/1/Zebstrika.BLW.42.mobile.jpg', 'Incomum'),
('Zebstrika', 'https://den-cards.pokellector.com/1/Zebstrika.BLW.43.mobile.jpg', 'Rara'),
('Joltik', 'https://den-cards.pokellector.com/1/Joltik.BLW.44.mobile.jpg', 'Comum'),
('Joltik', 'https://den-cards.pokellector.com/1/Joltik.BLW.45.mobile.jpg', 'Comum'),
('Galvantula', 'https://den-cards.pokellector.com/1/Galvantula.BLW.46.mobile.jpg', 'Rara'),
('Zekrom', 'https://den-cards.pokellector.com/1/Zekrom.BLW.47.mobile.jpg', 'Rara'),
('Munna', 'https://den-cards.pokellector.com/1/Munna.BLW.48.mobile.jpg', 'Incomum'),
('Musharna', 'https://den-cards.pokellector.com/1/Musharna.BLW.49.mobile.jpg', 'Rara'),
('Woobat', 'https://den-cards.pokellector.com/1/Woobat.BLW.50.mobile.jpg', 'Comum'),
('Swoobat', 'https://den-cards.pokellector.com/1/Swoobat.BLW.51.mobile.jpg', 'Incomum'),
('Venipede', 'https://den-cards.pokellector.com/1/Venipede.BLW.52.mobile.jpg', 'Comum'),
('Whirlipede', 'https://den-cards.pokellector.com/1/Whirlipede.BLW.53.mobile.jpg', 'Incomum'),
('Scolipede', 'https://den-cards.pokellector.com/1/Scolipede.BLW.54.mobile.jpg', 'Rara'),
('Solosis', 'https://den-cards.pokellector.com/1/Solosis.BLW.55.mobile.jpg', 'Comum'),
('Duosion', 'https://den-cards.pokellector.com/1/Duosion.BLW.56.mobile.jpg', 'Incomum'),
('Reuniclus', 'https://den-cards.pokellector.com/1/Reuniclus.BLW.57.mobile.jpg', 'Rara'),
('Timburr', 'https://den-cards.pokellector.com/1/Timburr.BLW.58.mobile.jpg', 'Comum'),
('Timburr', 'https://den-cards.pokellector.com/1/Timburr.BLW.59.mobile.jpg', 'Comum'),
('Gurdurr', 'https://den-cards.pokellector.com/1/Gurdurr.BLW.60.mobile.jpg', 'Incomum'),
('Throh', 'https://den-cards.pokellector.com/1/Throh.BLW.61.mobile.jpg', 'Rara'),
('Sawk', 'https://den-cards.pokellector.com/1/Sawk.BLW.62.mobile.jpg', 'Rara'),
('Sandile', 'https://den-cards.pokellector.com/1/Sandile.BLW.63.mobile.jpg', 'Comum'),
('Krokorok', 'https://den-cards.pokellector.com/1/Krokorok.BLW.64.mobile.jpg', 'Incomum'),
('Krookodile', 'https://den-cards.pokellector.com/1/Krookodile.BLW.65.mobile.jpg', 'Rara'),
('Purrloin', 'https://den-cards.pokellector.com/1/Purrloin.BLW.66.mobile.jpg', 'Comum'),
('Liepard', 'https://den-cards.pokellector.com/1/Liepard.BLW.67.mobile.jpg', 'Rara'),
('Scraggy', 'https://den-cards.pokellector.com/1/Scraggy.BLW.68.mobile.jpg', 'Comum'),
('Scrafty', 'https://den-cards.pokellector.com/1/Scrafty.BLW.69.mobile.jpg', 'Rara'),
('Zorua', 'https://den-cards.pokellector.com/1/Zorua.BLW.70.mobile.jpg', 'Comum'),
('Zoroark', 'https://den-cards.pokellector.com/1/Zoroark.BLW.71.mobile.jpg', 'Rara'),
('Vullaby', 'https://den-cards.pokellector.com/1/Vullaby.BLW.72.mobile.jpg', 'Incomum'),
('Mandibuzz', 'https://den-cards.pokellector.com/1/Mandibuzz.BLW.73.mobile.jpg', 'Rara'),
('Klink', 'https://den-cards.pokellector.com/1/Klink.BLW.74.mobile.jpg', 'Comum'),
('Klang', 'https://den-cards.pokellector.com/1/Klang.BLW.75.mobile.jpg', 'Incomum'),
('Klinklang', 'https://den-cards.pokellector.com/1/Klinklang.BLW.76.mobile.jpg', 'Rara'),
('Patrat', 'https://den-cards.pokellector.com/1/Patrat.BLW.77.mobile.jpg', 'Comum'),
('Patrat', 'https://den-cards.pokellector.com/1/Patrat.BLW.78.mobile.jpg', 'Comum'),
('Watchog', 'https://den-cards.pokellector.com/1/Watchog.BLW.79.mobile.jpg', 'Incomum'),
('Lillipup', 'https://den-cards.pokellector.com/1/Lillipup.BLW.80.mobile.jpg', 'Comum'),
('Lillipup', 'https://den-cards.pokellector.com/1/Lillipup.BLW.81.mobile.jpg', 'Comum'),
('Herdier', 'https://den-cards.pokellector.com/1/Herdier.BLW.82.mobile.jpg', 'Incomum'),
('Stoutland', 'https://den-cards.pokellector.com/1/Stoutland.BLW.83.mobile.jpg', 'Rara'),
('Pidove', 'https://den-cards.pokellector.com/1/Pidove.BLW.84.mobile.jpg', 'Comum'),
('Tranquill', 'https://den-cards.pokellector.com/1/Tranquill.BLW.85.mobile.jpg', 'Incomum'),
('Unfezant', 'https://den-cards.pokellector.com/1/Unfezant.BLW.86.mobile.jpg', 'Rara'),
('Audino', 'https://den-cards.pokellector.com/1/Audino.BLW.87.mobile.jpg', 'Incomum'),
('Minccino', 'https://den-cards.pokellector.com/1/Minccino.BLW.88.mobile.jpg', 'Comum'),
('Cinccino', 'https://den-cards.pokellector.com/1/Cinccino.BLW.89.mobile.jpg', 'Rara'),
('Bouffalant', 'https://den-cards.pokellector.com/1/Bouffalant.BLW.90.mobile.jpg', 'Incomum'),
('Bouffalant', 'https://den-cards.pokellector.com/1/Bouffalant.BLW.91.mobile.jpg', 'Rara'),
('Energy Retrieval', 'https://den-cards.pokellector.com/1/Energy-Retrieval.BLW.92.mobile.jpg', 'Incomum'),
('Energy Search', 'https://den-cards.pokellector.com/1/Energy-Search.BLW.93.mobile.jpg', 'Comum'),
('Energy Switch', 'https://den-cards.pokellector.com/1/Energy-Switch.BLW.94.mobile.jpg', 'Incomum'),
('Full Heal', 'https://den-cards.pokellector.com/1/Full-Heal.BLW.95.mobile.jpg', 'Incomum'),
('PlusPower', 'https://den-cards.pokellector.com/1/PlusPower.BLW.96.mobile.jpg', 'Incomum'),
('Poke Ball', 'https://den-cards.pokellector.com/1/Poke-Ball.BLW.97.mobile.jpg', 'Incomum'),
('Pokedex', 'https://den-cards.pokellector.com/1/Pokedex.BLW.98.mobile.jpg', 'Incomum'),
('Pokemon Communication', 'https://den-cards.pokellector.com/1/Pokemon-Communication.BLW.99.mobile.jpg', 'Incomum'),
('Potion', 'https://den-cards.pokellector.com/1/Potion.BLW.100.mobile.jpg', 'Comum'),
('Professor Juniper', 'https://den-cards.pokellector.com/1/Professor-Juniper.BLW.101.mobile.jpg', 'Incomum'),
('Revive', 'https://den-cards.pokellector.com/1/Revive.BLW.102.mobile.jpg', 'Incomum'),
('Super Scoop Up', 'https://den-cards.pokellector.com/1/Super-Scoop-Up.BLW.103.mobile.jpg', 'Incomum'),
('Switch', 'https://den-cards.pokellector.com/1/Switch.BLW.104.mobile.jpg', 'Incomum'),
('Grass Energy', 'https://den-cards.pokellector.com/1/Grass-Energy.BLW.105.mobile.jpg', 'Comum'),
('Fire Energy', 'https://den-cards.pokellector.com/1/Fire-Energy.BLW.106.mobile.jpg', 'Comum'),
('Water Energy', 'https://den-cards.pokellector.com/1/Water-Energy.BLW.107.mobile.jpg', 'Comum'),
('Lightning Energy', 'https://den-cards.pokellector.com/1/Lightning-Energy.BLW.108.mobile.jpg', 'Comum'),
('Psychic Energy', 'https://den-cards.pokellector.com/1/Psychic-Energy.BLW.109.mobile.jpg', 'Comum'),
('Fighting Energy', 'https://den-cards.pokellector.com/1/Fighting-Energy.BLW.110.mobile.jpg', 'Comum'),
('Darkness Energy', 'https://den-cards.pokellector.com/1/Darkness-Energy.BLW.111.mobile.jpg', 'Comum'),
('Metal Energy', 'https://den-cards.pokellector.com/1/Metal-Energy.BLW.112.mobile.jpg', 'Comum'),
('Reshiram', 'https://den-cards.pokellector.com/1/Reshiram.BLW.113.mobile.jpg', 'Ultra rara'),
('Zekrom', 'https://den-cards.pokellector.com/1/Zekrom.BLW.114.mobile.jpg', 'Ultra rara'),
('Pikachu', 'https://den-cards.pokellector.com/1/Pikachu.BLW.115.mobile.jpg', 'Secreta rara');